23/11/20 (14:23:02) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:03) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:05) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:40) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:24:08) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:24:19) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/12/20 (15:06:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
24/12/20 (11:37:29) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
24/12/20 (11:38:00) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 872, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 665, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
26/12/20 (10:29:25) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
26/12/20 (10:35:40) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 872, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 665, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
27/12/20 (09:40:56) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
27/12/20 (10:33:16) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
27/12/20 (10:33:38) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
27/12/20 (10:41:17) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 824, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
27/12/20 (19:02:41) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
28/12/20 (11:48:00) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (20:59:30) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (21:00:10) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (21:14:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (21:20:39) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (22:38:09) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/12/20 (23:04:35) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 872, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 665, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
30/12/20 (17:33:14) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
30/12/20 (17:33:52) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
30/12/20 (17:34:08) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
30/12/20 (17:34:13) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
30/12/20 (17:51:51) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (11:46:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (12:17:38) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (12:50:10) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (14:13:43) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (14:14:01) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
31/12/20 (14:34:12) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (15:48:28) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (15:48:31) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
31/12/20 (17:12:24) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (17:12:25) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
31/12/20 (17:12:45) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (17:12:51) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
31/12/20 (17:13:45) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (17:18:43) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (17:31:07) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (17:31:35) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
31/12/20 (19:28:47) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (19:35:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/12/20 (19:35:13) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 879, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 672, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
01/01/21 (09:36:08) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1206, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:33:25) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:36:47) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:38:42) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:38:44) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:40:26) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:41:05) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:41:22) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:41:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:42:27) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:45:52) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:46:55) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:47:12) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:47:38) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:51:11) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:51:26) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:51:53) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:52:31) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (14:52:46) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (15:43:32) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (15:43:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (15:44:15) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 880, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 673, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
01/01/21 (16:28:20) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (16:29:43) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 880, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 673, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
01/01/21 (21:19:02) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/01/21 (21:19:16) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 880, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 673, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
01/01/21 (21:34:14) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
02/01/21 (10:37:16) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (09:16:14) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (09:33:48) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (13:30:05) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1207, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (16:53:59) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (16:54:16) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (17:02:06) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (17:02:10) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (17:11:12) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (17:11:56) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (17:12:20) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (17:12:25) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (20:28:49) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (20:30:10) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (20:32:56) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (20:51:25) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (20:51:47) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (21:02:57) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (21:11:41) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (21:12:19) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (21:12:23) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
03/01/21 (21:35:53) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/01/21 (21:36:22) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
04/01/21 (10:28:35) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
04/01/21 (10:28:42) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
04/01/21 (10:35:13) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
04/01/21 (15:31:28) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
04/01/21 (16:28:30) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (10:47:51) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (10:48:46) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (10:48:54) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (10:58:33) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (15:33:13) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (15:33:25) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (16:42:26) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (16:45:09) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 882, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 675, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (17:23:24) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (17:23:33) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1209, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (17:24:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (17:24:16) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (17:39:35) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (18:28:47) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (18:28:51) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
05/01/21 (21:03:57) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
05/01/21 (21:04:03) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (08:06:55) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (08:07:00) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (08:42:30) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (08:44:46) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (09:40:54) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (09:41:06) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (10:02:22) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (10:02:27) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (14:45:15) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (14:50:03) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (14:54:24) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (14:54:37) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (15:28:40) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (15:44:15) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (15:44:40) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/01/21 (16:05:04) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (16:22:14) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (16:24:28) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (17:19:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (17:24:26) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (17:44:19) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (18:23:18) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (18:45:35) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1222, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
06/01/21 (18:45:58) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 895, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 688, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
07/01/21 (10:20:53) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
07/01/21 (10:21:19) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 901, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 694, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
07/01/21 (11:20:24) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
07/01/21 (13:39:26) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
07/01/21 (14:21:13) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
07/01/21 (14:53:48) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
07/01/21 (15:02:03) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 901, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 694, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
08/01/21 (15:23:44) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
08/01/21 (15:24:15) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 901, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 694, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
09/01/21 (14:20:46) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1253, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/01/21 (11:02:20) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/01/21 (19:04:48) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/01/21 (10:56:53) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/01/21 (11:31:50) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/01/21 (14:07:45) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/01/21 (21:44:40) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/01/21 (21:44:49) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 914, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 707, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
15/01/21 (15:49:40) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
19/01/21 (12:07:03) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
19/01/21 (12:09:32) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/02/21 (21:13:56) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1319, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/02/21 (21:14:08) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 967, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 760, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
01/02/21 (21:14:48) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1319, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
01/02/21 (21:27:13) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 967, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 760, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
02/02/21 (17:53:32) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1319, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/02/21 (14:15:17) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1319, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
08/03/21 (14:25:16) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
08/03/21 (18:36:18) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
08/03/21 (18:39:29) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
10/03/21 (08:48:07) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
10/03/21 (08:48:13) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 975, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 768, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
10/03/21 (15:59:46) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (09:01:20) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (09:22:56) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (09:29:54) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (09:47:10) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (12:01:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/03/21 (12:02:02) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
16/03/21 (11:41:32) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
29/03/21 (08:57:05) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/04/21 (17:24:12) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
09/04/21 (18:59:23) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
20/04/21 (13:39:41) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
23/04/21 (10:13:43) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
08/05/21 (22:31:20) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1335, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/05/21 (19:20:10) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1335, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
13/05/21 (17:09:58) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1335, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
24/05/21 (11:26:38) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1335, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
03/07/21 (17:27:15) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
22/07/21 (13:41:17) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
27/07/21 (11:19:36) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
27/07/21 (11:24:21) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
31/07/21 (14:51:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
09/08/21 (21:46:49) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/08/21 (10:58:36) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
11/08/21 (21:08:02) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
12/08/21 (22:33:51) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
